export const BUTTONS = {
	"1":  { type: "simple",  value: "1" },
	"2":  { type: "simple",  value: "2" },
	"3":  { type: "simple",  value: "3" },
	"4":  { type: "simple",  value: "4" },
	"5":  { type: "simple",  value: "5" },
	"6":  { type: "simple",  value: "6" },
	"7":  { type: "simple",  value: "7" },
	"8":  { type: "simple",  value: "8" },
	"9":  { type: "simple",  value: "9" },
	"0":  { type: "simple",  value: "0" },
	".":  { type: "simple",  value: "." },
	"+":  { type: "simple",  value: "+" },
	"-":  { type: "simple",  value: "-" },
	"×":  { type: "simple",  value: "\\times" },
	"÷":  { type: "simple",  value: "\\div" },
	"%":  { type: "simple",  value: "\\%" },
	"√":  { type: "simple",  value: "\\sqrt{" },
	"(":  { type: "simple",  value: "(" },
	")":  { type: "special", value: "close" },
	"AC": { type: "special", value: "clear" },
	"⌫":  { type: "special", value: "delete" },
	"=":  { type: "special", value: "submit" }
}
